### ISSUE TITLE
Any updates?

### ISSUE THREAD

**Issue by jizusun** [openui5/packaged-sap.ui.documentation#1]
Is this package is for the source code of https://openui5.hana.ondemand.com/?

I'm so looking forward to it :heart_eyes:

**Comment by Michadelic** [comment]
Yes, it is. Partly at least - documentation and API reference are generated and put together from other sources. Demo Apps, Samples, Tools, and the demo kit application including the landing pages is in this package.

Note that all used controls are from sap.m and sap.tnt, just the app itself is shipped in this package

**Comment by jizusun** [comment]
Awesome that UI5 is open-sourcing more tools!
Thanks UI5 team!
